# Travis CI integration for p4c using Docker.

services:
  - docker

install:
  - docker build -t p4c-xdp .

script:
  - docker run --privileged -w /home/p4c/build -e CTEST_PARALLEL_LEVEL p4c-xdp ctest -R xdp --output-on-failure --schedule-random
  - ls $HOME/.ccache

notifications:
  email:
    recipients:
      - tuc@vmware.com
      - mbudiu@vmware.com

