# Travis CI integration for p4c using Docker.
sudo: required

services:
  - docker

install:
  - docker build -t p4c-xdp .

script:
  - docker run --privileged -w /tmp/p4c-xdp/tests p4c-xdp ./test_iproute.sh

notifications:
  email:
    recipients:
      - tuc@vmware.com
      - mbudiu@vmware.com

