# Travis CI integration for p4c using Docker.

sudo: required
dist: xenial

services:
  - docker

env:
  - CTEST_PARALLEL_LEVEL=4

install:
  - sudo docker build -t p4c-xdp .

script:
  - sudo docker run --privileged -w /home/p4c/build -e CTEST_PARALLEL_LEVEL p4c-xdp ctest -R xdp --output-on-failure --schedule-random

notifications:
  email:
    recipients:
      - tuc@vmware.com
      - mbudiu@vmware.com

