# Travis CI integration for p4c using Docker.

services:
  - docker

install:
  - docker build -t p4c-xdp .

script:
  - docker run -w /home/p4c/extensions/p4c-xdp/tests p4c-xdp make

notifications:
  email:
    recipients:
      - tuc@vmware.com
      - mbudiu@vmware.com

