/*
Copyright 2018 VMware, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
 * This file contains all functions and definitions necessary for the xdp target C code to compile. It must be included with any file generated by the p4c-xdp compiler.
 */

#ifndef __BPF_HELPERS_H
#define __BPF_HELPERS_H

#include "ebpf_kernel.h"

/* xdp descriptor similar to sk_buff */
#ifdef SK_BUFF
#undef SK_BUFF
#endif
#define SK_BUFF struct xdp_md

#ifdef load_dword
#undef load_dword
#endif

#define load_dword(data, b) (*(u64 *)((u8*)(data) + (b))) << 16



#endif
