/*
 * Tool for accessing eBPF maps generated by P4, at tests/
 * gcc -I ../lib/ ../lib/libbpf.o user_xdp5.c  
 */
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <stdio.h>
#include <unistd.h>
#include <linux/bpf.h>
#include <errno.h>
#include <string.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <stdint.h>
#include <assert.h>
#include "libbpf.h"

#define CONTROL_PLANE 1
#include "xdp5.h"

// we might want to put this into header
#define TABLE "/dstmactable"

int main(void)
{
	int ret;	
    int fd;
	struct dstmactable_key key;
	struct dstmactable_value value;

    /* populate the default table */
	initialize_tables();

	value.action = Fallback_action;
	key.field0 = 0x800; // IP packet

    printf("=== Open BPF map: %s ===\n", MAP_PATH TABLE);
    fd = bpf_obj_get(MAP_PATH TABLE);
    if (fd < 0) {
        printf("BPF map %s not loaded\n", MAP_PATH TABLE);
        exit(1);
    }

    /* populate the match-action table */
    printf("=== Write to eBPF map ===\n");
    printf("key = %x value = %x\n", key.field0, value.action);
    ret = bpf_update_elem(fd, &key, &value, BPF_ANY);
    if (ret) {
        perror("error updating map element\n");
        exit(1);
    }

    close(fd);
    return 0;
}

