/*
 * Tool for accessing eBPF maps generated by P4, at tests/
 * gcc -I ../lib/ ../lib/libbpf.o user_xdp10.c -o xdp10 
 */
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <stdio.h>
#include <unistd.h>
#include <linux/bpf.h>
#include <errno.h>
#include <string.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <stdint.h>
#include <assert.h>
#include "libbpf.h"

#include "xdp10.h"

#define TABLE "/dstmactable"
#define STATS "/counters"

int main(void)
{
	int ret;	
    int fd, i;
    struct in_addr addr;
    counters_key key;
    counters_value value;

    inet_aton("10.2.2.9", &addr);
    memcpy(&key, &addr, 4);
    key = ntohl(key);

    printf("=== Open BPF map: %s ===\n", MAP_PATH STATS);
    fd = bpf_obj_get(MAP_PATH STATS);
    if (fd < 0) {
        printf("BPF map %s not loaded\n", MAP_PATH STATS);
        exit(1);
    }

    /* populate the match-action table */
    for (i = 0; i < 10; i++) {
        printf("=== Lookup to eBPF map ===\n");
        ret = bpf_lookup_elem(fd, &key, &value);
        if (!ret)
            printf("counter = %d\n", value);
        sleep(1);
    }
    close(fd);
    return 0;
}

